name: Changelog

on:
  workflow_dispatch:
    inputs:
      version:
        required: false
        default: ''

permissions:
  contents: write
  pull-requests: write

jobs:
  changelog:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Inputs
        uses: Payadel/inputs@v0.2.3
        id: inputs
        with:
          inputs: |
            - name: version
              default: ''
            - name: current-branch-name
              default: '$(git rev-parse --abbrev-ref HEAD)'

      - name: Run Changelog
        uses: payadel/changelog-sv-action@v0.0.6
        id: changelog
        with:
          version: ${{ steps.inputs.outputs.version }}

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          commit-message: "chore(changelog): update CHANGELOG.md for v${{ steps.changelog.outputs.version }}"
          branch: changelog
          delete-branch: true
          title: 'Changelog v${{ steps.changelog.outputs.version }}'
          body: ${{ steps.changelog.outputs.changelog }}
          assignees: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
